experiment_config:
  multiclass:
    - embryo
    - debris
  gpu_id: 0
  
model:
  backbone: vgg16_bn
  architecture: mlp_two_stage
  stage_one_model_path: outputs/results/debris_normalizedce_oneall/weights/best_f1.pth
  row: 1
  line: 1

training:
  lr: 0.001
  lr_backbone: 0.00001
  epochs: 200
  batch_size: 3
  num_patches: 4
  patch_size: 512
  scale: false
  sharpness: true
  equalize: false

loss_params:
  loss:
    - labels
    - points
  ce_coef:
    - 1.0
  point_loss_coef: 0.0002
  aux_loss_coef: 0.2
  debris_class_idx: 2
  debris_radius: 5
  neg_lambda_debris: 1.0
  neg_lambda_other: 10.0 
  normalized_ce: true

evaluation:
  eval_freq: 1